# Docker-compose 1.6 or better
version: '2'
services:
  xnat-postgres:
    build: ./postgres/
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
  
  xnat:
    build:
      context: ./builder/
      args:
        XNAT_VERSION: "1.6.4"
    ports:
      - "8080:8080"
    links:
      - "xnat-postgres:postgres"
    environment:
      XNAT_VERSION: "1.6.4"
      PROJECT_NAME: "xnat-1.6.4"
      SITE_TITLE: "XNAT-1.6.4"
